source(here::here("R", "utilities.R"))

# Load data ====================================================================

load(here("data", "tidy", "fb_matched.Rda"))

gender_data <- fb_matched

# Creating firstname columns using the stringr package =========================

gender_data$senate$firstname <- word(gender_data$senate$candidate, 1)
gender_data$house$firstname <- word(gender_data$house$candidate, 1)

# Attempts to figure out gender package ========================================

# Gender returns a tibble, not simply a column...will need to merge
senate_gender <- gender(
  gender_data$senate$firstname,
  years = c(1933, 1995), # Range from oldest MC's birth year to 25-as-of-2020
  method = c("ssa"), # Social Security names
  countries = c("United States") # Somewhat flawed -- not all will be born in US
)

senate_gen <- as.data.frame(cbind(senate_gender$name, senate_gender$gender))
colnames(senate_gen) <- c("firstname", "gender")

# Merging Senate Dataset =======================================================

# The tibble generated by `gender` will have the same number of rows as the name
# vector (gender_data$senate$firstname) that was used to create it. If we try to
# merge with this, it won't work -- we need to take out the duplicate rows first

unique_senate_gen <- unique(senate_gen)
gender_data$senate <- merge(gender_data$senate, unique_senate_gen, 
                            by = "firstname")

# House ========================================================================

house_gender <- gender(
  gender_data$house$firstname,
  years = c(1933, 1995), # Range from oldest MC's birth year to 25-as-of-2020
  method = c("ssa"), # Social Security names
  countries = c("United States") # Somewhat flawed -- not all will be born in US
)

house_gen <- as.data.frame(cbind(house_gender$name, house_gender$gender))
colnames(house_gen) <- c("firstname", "gender")
unique_house_gen <- unique(house_gen)

gender_data$house <- merge(gender_data$house, unique_house_gen, 
                            by = "firstname")

